### ISSUE TITLE
document errors in AC Transit Routes.txt import process

### ISSUE THREAD

**Issue by tbuckl** [MetropolitanTransportationCommission/RegionalTransitDatabase#1]
Importing current 511 Routes data (pulled like [this](https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/master/python/get_511_gtfs_zips.py)) for `AC Transit` into MS SQL Server using Studio fails to update using the legacy import script lines [here](
https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/76ace34d5bcfcc81d4f16848739e6688a161b227/sql/etl/ROUTES.sql#L18-L25).  The result is that 0 rows are updated. 

I tried different line endings, which seemed to work for importing other tables. See, for example, [this commit](https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/commit/dbb07b0b2179565196f7e73c856917e6d64447e8#diff-1b9eaeefab96d8bfe38723f5b528468eR12). 

That resulted in the following error:

```
Bulk load: An unexpected end of file was encountered in the data file.
Msg 7399, Level 16, State 1, Line 1
The OLE DB provider "BULK" for linked server "(null)" reported an error. The provider did not give any information about the error.
Msg 7330, Level 16, State 2, Line 1
Cannot fetch a row from OLE DB provider "BULK" for linked server "(null)".
```

At which point, studio/sql server did not complete the query execution and no rows were imported. 

I also tried different [data types](https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/commit/5cc70763a55dbba1c086696a94c8039bf4494264), which did not resolve above issue. 

Since it appears that the data contains errors, the next step was to try a different data provider. Mapzen's Transit.Land site lists a direct link to an AC Transit url with GTFS data [here](https://transit.land/feed-registry/operators/o-9q9-actransit). 

SQL Server/Studio also did not like these data, but for different reasons. Now I started [logging import errors from the original script](https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/commit/3fff5412606b9657a5233845937325a497be9fb3). SQL Server/Studio spits out cryptic error messages. For example, here is the error message it spat out for the AC Transit data directly from the source:

```
Row 81 File Offset 9091 ErrorFile Offset 0 - HRESULT 0x80004005
```

which it says refers to this row (actually 2 rows, weirdly, even though its only 1 in the data):
```
AC Transit,Z-138,Z,San Francisco - Albany,3
AC Transit,Z-138,Z,San Francisco - Albany,3
```

Thankfully, DataGrip provides more helpful error messages. The data from 511 outputs this error during import:

```
159:45: actual: end of file, expected: value
```

Which seems like a line-ending problem in the routes.txt file from 511. 

No errors are thrown in importing the GTFS data directly from AC Transit in datagrip.

**Comment by Keareys** [comment]
There is an issue with the GTFS tables that needs to be fixed first. The GTFS text files have issues with apostrophes in the record names.

**Comment by Keareys** [comment]
You will also need to check the column names in the GTFS feed tables to make sure they match the schema of the tables. I had to do a fair amount of text processing for the tables using sublime.

**Comment by Keareys** [comment]
Based upon your comments, it appears that the format of the data is different when downloading from an AC transit source other than 511?  At this point, we cannot change the data source, so I'd prefer we work out a solution (which I have done in the past) that fixes the errors in the 511 API output.  We can log these issues with the 511 API support team to see if they can correct the problem.  This will be a long term fix I'm sure, so let's focus on fixing the problem with the 511 API GTFS tables.  Let me know if you have any questions.

**Comment by tbuckl** [comment]
thanks @Keareys i'll look into fixing the data from 511 before import.

**Comment by tbuckl** [comment]
this seems to have been obviated/resolved here: https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/4
