### ISSUE TITLE
check on SF route 48 stops/geometry discrepancy

### ISSUE THREAD

**Issue by tbuckl** [MetropolitanTransportationCommission/RegionalTransitDatabase#31]
it seems like this function is making selections about service:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/4ed7ebc5bac9d121ca4a4beb90009dd5cf51639b/R/r511.R#L72-L79

we could potentially use the start and end dates in this file for a more granular selection, assuming providers have them filled out:

https://developers.google.com/transit/gtfs/reference/calendar-file

**Comment by tbuckl** [comment]
these 4 functions together give us weird results for the MA provider:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/8c261e97cf088deb0e3e6077db7039f9fda243c7/R/make_weekday_peak_bus_stops_csv.R#L50-L54

in particular, we end up with just 4 pm stops for 2 routes that have a headway below 16 minutes. need to check whether that route has more than 2 stops each

**Comment by Keareys** [comment]
I suggest that we perhaps use the calendar and stop times to choose the max number of trips by route and use this number for the headway. Effectively filtering out different patterns schedules.

**Comment by tbuckl** [comment]
for now, using a specific date: 
https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/simplify/R/r511.R#L291

changing the title to indicate that we need to review this. may be related to:

https://github.com/MetropolitanTransportationCommission/fast-trips/issues/71

**Comment by tbuckl** [comment]
this function:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/simplify/R/r511.R#L134-L141

which is based on this deduplication technique:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/simplify/R/RouteBuilderStuff_KS.R#L281-L289

seems to hang on to stops for route 48 in san francisco that aren't on any high frequency route geometries. for a map of these stops, routes, see:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/43

**Comment by tbuckl** [comment]
moving this to the second draft output from a refactor as its now higher priority.

**Comment by tbuckl** [comment]
![hf_stops_routes](https://user-images.githubusercontent.com/98956/27106579-d1567cc0-5048-11e7-98c8-0ff8ab64da22.PNG)
confusingly, some stops, such as `16144`, show in the image for SF have M/T/W/T/F service, yet the route geometries do not show the route passing by those stops. checking on all services for route 48

**Comment by tbuckl** [comment]
as discussed here:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/43
