### ISSUE TITLE
Confirm buffer methodology for TPAs

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/RegionalTransitDatabase#43]
Just to confirm, the buffers should be as follows:

1. All HF Bus route lines are 1/4 buffer. Not the stops, just the lines.
2. HF Bus Stops that are within 0.2 miles of a HF bus stop (which is served by a different route) is buffered 1/2 mile
3. All Rail, Ferry and Light Rail stops (Planned and Existing) are buffered 1/2 Mile.

Generate these buffered features as individual FCs so that I can review. Ensure that the attribute table contains attributes for each system type, and buffer distance.

**Comment by tbuckl** [comment]
Thanks @Keareys, (1) and (3) are now the top layers on the map. 

Lets talk in person about (2)

**Comment by tbuckl** [comment]
some context for (2) is shown below in our "HF Stops" list for SF route 48.  here we see "HF Stops" that are not on "HF Route"s. 

![hf_stops_routes](https://user-images.githubusercontent.com/98956/27095127-7ecf5a02-5021-11e7-8970-dc044782c3e2.PNG)

i assume we want to grab those and then buffer around them. 

i am currently working on https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/41. 

please let me know if you would like to switch to this.

**Comment by tbuckl** [comment]
hopefully we can address (2) in https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/31

**Comment by tbuckl** [comment]
also, (2) depends on https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/46

**Comment by tbuckl** [comment]
confirmed here: https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/master/docs/transit_priority_areas.md#confirm-the-buffer-methodology
