### ISSUE TITLE
might need to filter high frequency stops using both ways/loop and am/pm criteria, and service

### ISSUE THREAD

**Issue by tbuckl** [MetropolitanTransportationCommission/RegionalTransitDatabase#45]

**Comment by Keareys** [comment]
I might need more context for this issue. I don't follow what the issue is intending to fix.

**Comment by tbuckl** [comment]
done here https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/master/R/priority_routes/identify_bus_tpas_and_output_geometries.R#L194-L195
