### ISSUE TITLE
interpolate stop_times for all operators

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/RegionalTransitDatabase#5]
When building the master tables for all operators, blank stop_times will need to be interpolated for each operator.  The R-script generates the master table, but also needs to be updated to fix the stop_times that are blank.  

Use the Transit Tools script (ArcGIS Toolbox) to fix this (Interpolate Blank Stop Times).  

<img width="650" alt="interpolatestoptimes" src="https://cloud.githubusercontent.com/assets/6600484/25671250/13506b70-2fe4-11e7-9157-82cd7aedcf18.png">

  
  
In addition, any stop_times that are greater than 24 hours need to be adjusted.  There is a sql script that should handle this, however you can also use a text editor like text wrangler to fix those stops that have a time greater than 24 hrs.  

For Example:  

25: should be 01:  
26: should be 02:  
.  
.  
.  
35: should be 11:  
.  
.  
.

**Comment by tbuckl** [comment]
this script can help with doing the interpolation for each operator:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/blob/master/python/preprocess_gtfs_folders.py

i'll double check that its been done on the csv's that i'm currently loading into the db.

**Comment by tbuckl** [comment]
to confirm, the data in the db has no null values for arrival and departure time in the `stop_times` table. 

i started a pseudo processing steps list here:

https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase#steps

we can think about turning this into a Makefile later.

**Comment by tbuckl** [comment]
@Keareys ok if we close this one out?

**Comment by tbuckl** [comment]
https://github.com/MetropolitanTransportationCommission/RegionalTransitDatabase/issues/18 may be related
